### ISSUE TITLE
Seems to be an older version

### ISSUE THREAD

**Issue by jakobklein** [jukofyork/aiassistant#2]
Hi, I found your comments on the parent-project (gradusnikov) very helpful and was hoping that your fork would incorporate these ideas.

I built the Plugin as described but the preferences dialog is all about OpenAI.
Instead of "Ollama API Base Address" (like in the screenshot) I get "OpenAI API Base Address" and "OpenAI API Key"
My local ollama installation seems to be working correctly since it responds on http://127.0.0.1:11434

I guess the latest sources (of the version shown in the screenshots on your github project page) are not on github since I didn't find any hint to "ollama" neither in PreferencePage.java nor in the rest of the plugin-code.

**Comment by jukofyork** [comment]
Yeah, I removed all the stuff that uses the Ollama API as it was too buggy and since then Ollama added an Open AI compatable API it isn't really needed anymore.

You can still use it will Ollama if you add `/v1` to the URL, but it won't show the list of models like is did before:

```
http://localhost:11434/v1/
```

or possibly:

```
http://localhost:11434/v1
```

I do plan to add the ability to get a list of models again, but all the OpenAI compatable servers have a slightly different way of listing the model names.

Once I've done that I will redo all the screenshots for Github as there are quite a lot of improvements I've added since them:

- Spell checking in the user input box.
- More right click options for the AI page.
- Reloads the AI pages on open/close.

and a lot of other little tweaks.

**Comment by jakobklein** [comment]
Thanks alot for the quick answer. 
Got it running with ollama and llama3.2:latest and I am amazed by the features you added.

**Comment by jukofyork** [comment]
> Thanks alot for the quick answer. Got it running with ollama and llama3.2:latest and I am amazed by the features you added.

No problem and glad you got it going!

I also removed a lot of features from Wojciech's version:

- The LLM "function-calling" stuff as it didn't really seem to work well with local LLMs and in general didn't seem all that useful.
- Anything that was Java-specific like the code Wojciech had written to parse the AST of the Java source files (I wanted it to work with C++ via Eclipse CDT, Python via PyDev, etc).
- I had to remove all the `@inject` Dependency Injection stuff as it was a huge source of really weird `NullPointerException` bugs... Sadly I think these were probably 99% of the reason people struggled to get Wojciech's version working and why he might have stopped working on it :/

The only things left on my ToDo list of things to add are:

- Add back the model selection stuff (possibly on the main view instead of in the settings pages so much easier to switch models).
- Add code to export the chat as a text file in Markdown.
- See if I can add either multiple views and/or a branching chat (eg: undo, redo, left child, right child tree traversing like a lot of LLM frontends use).
- Try to get LaTeX working using KaTeX or MathJax (I've tried this a couple of times without managing to figure it out sadly).

**Comment by jukofyork** [comment]
I've added back the ability to get the model list but only tested it on `openrouter` and `openai`, so not sure if it works with `ollama` or `llama.cpp`'s server...

Beware the settings page is very buggy unless you quit and reopen it and `Apply` and `Restore Defaults` don't work properly a lot of the time (I'll try and get to the bottom of this later).

**Comment by jukofyork** [comment]
I'd hold off as the current method isn't really usable at all:

https://github.com/jukofyork/aiassistant/discussions/4

**Comment by jukofyork** [comment]
@jakobklein

I finally updated the readme and added a proper v1.0 release version if you are still using this. I think it's pretty much feature complete now for my use case so doubt much will change from now.
